(library (system configuration user-settings-group)
  (export new is? user-settings-group?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...)
         #'(clr-new System.Configuration.UserSettingsGroup a ...)))))
  (define (is? a) (clr-is System.Configuration.UserSettingsGroup a))
  (define (user-settings-group? a)
    (clr-is System.Configuration.UserSettingsGroup a)))
