(library (system reflection emit op-code-names)
  (export new is? op-code-names?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...)
         #'(clr-new System.Reflection.Emit.OpCodeNames a ...)))))
  (define (is? a) (clr-is System.Reflection.Emit.OpCodeNames a))
  (define (op-code-names? a)
    (clr-is System.Reflection.Emit.OpCodeNames a)))
