(library (system dll-not-found-exception)
  (export new is? dll-not-found-exception?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...) #'(clr-new System.DllNotFoundException a ...)))))
  (define (is? a) (clr-is System.DllNotFoundException a))
  (define (dll-not-found-exception? a)
    (clr-is System.DllNotFoundException a)))
