(library (system field-access-exception)
  (export new is? field-access-exception?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...) #'(clr-new System.FieldAccessException a ...)))))
  (define (is? a) (clr-is System.FieldAccessException a))
  (define (field-access-exception? a)
    (clr-is System.FieldAccessException a)))
