(library (mono xml xsl yy-parser yy-unexpected-eof)
  (export new is? yy-unexpected-eof?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...)
         #'(clr-new Mono.Xml.Xsl.yyParser.yyUnexpectedEof a ...)))))
  (define (is? a) (clr-is Mono.Xml.Xsl.yyParser.yyUnexpectedEof a))
  (define (yy-unexpected-eof? a)
    (clr-is Mono.Xml.Xsl.yyParser.yyUnexpectedEof a)))
