(library (jet-brains annotations linq-tunnel-attribute)
  (export new is? linq-tunnel-attribute?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...)
         #'(clr-new JetBrains.Annotations.LinqTunnelAttribute a ...)))))
  (define (is? a) (clr-is JetBrains.Annotations.LinqTunnelAttribute a))
  (define (linq-tunnel-attribute? a)
    (clr-is JetBrains.Annotations.LinqTunnelAttribute a)))
