(library (unity-engine cpp-include-attribute)
  (export new is? cpp-include-attribute?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...) #'(clr-new UnityEngine.CppIncludeAttribute a ...)))))
  (define (is? a) (clr-is UnityEngine.CppIncludeAttribute a))
  (define (cpp-include-attribute? a)
    (clr-is UnityEngine.CppIncludeAttribute a)))
