(library (unity-engine not-renamed-attribute)
  (export new is? not-renamed-attribute?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...) #'(clr-new UnityEngine.NotRenamedAttribute a ...)))))
  (define (is? a) (clr-is UnityEngine.NotRenamedAttribute a))
  (define (not-renamed-attribute? a)
    (clr-is UnityEngine.NotRenamedAttribute a)))
