(library (unity-engine rect-transform-utility)
  (export is?
          rect-transform-utility?
          flip-layout-axes
          pixel-adjust-rect
          calculate-relative-rect-transform-bounds
          screen-point-to-world-point-in-rectangle?
          pixel-adjust-point
          flip-layout-on-axis
          world-to-screen-point
          screen-point-to-local-point-in-rectangle?
          screen-point-to-ray
          rectangle-contains-screen-point?)
  (import (ironscheme-clr-port))
  (define (is? a) (clr-is UnityEngine.RectTransformUtility a))
  (define (rect-transform-utility? a)
    (clr-is UnityEngine.RectTransformUtility a))
  (define-method-port
    flip-layout-axes
    UnityEngine.RectTransformUtility
    FlipLayoutAxes
    (static:
      System.Void
      UnityEngine.RectTransform
      System.Boolean
      System.Boolean))
  (define-method-port
    pixel-adjust-rect
    UnityEngine.RectTransformUtility
    PixelAdjustRect
    (static:
      UnityEngine.Rect
      UnityEngine.RectTransform
      UnityEngine.Canvas))
  (define-method-port
    calculate-relative-rect-transform-bounds
    UnityEngine.RectTransformUtility
    CalculateRelativeRectTransformBounds
    (static: UnityEngine.Bounds UnityEngine.Transform)
    (static:
      UnityEngine.Bounds
      UnityEngine.Transform
      UnityEngine.Transform))
  (define-method-port
    screen-point-to-world-point-in-rectangle?
    UnityEngine.RectTransformUtility
    ScreenPointToWorldPointInRectangle
    (static:
      System.Boolean
      UnityEngine.RectTransform
      UnityEngine.Vector2
      UnityEngine.Camera
      UnityEngine.Vector3&))
  (define-method-port
    pixel-adjust-point
    UnityEngine.RectTransformUtility
    PixelAdjustPoint
    (static:
      UnityEngine.Vector2
      UnityEngine.Vector2
      UnityEngine.Transform
      UnityEngine.Canvas))
  (define-method-port
    flip-layout-on-axis
    UnityEngine.RectTransformUtility
    FlipLayoutOnAxis
    (static:
      System.Void
      UnityEngine.RectTransform
      System.Int32
      System.Boolean
      System.Boolean))
  (define-method-port
    world-to-screen-point
    UnityEngine.RectTransformUtility
    WorldToScreenPoint
    (static:
      UnityEngine.Vector2
      UnityEngine.Camera
      UnityEngine.Vector3))
  (define-method-port
    screen-point-to-local-point-in-rectangle?
    UnityEngine.RectTransformUtility
    ScreenPointToLocalPointInRectangle
    (static:
      System.Boolean
      UnityEngine.RectTransform
      UnityEngine.Vector2
      UnityEngine.Camera
      UnityEngine.Vector2&))
  (define-method-port
    screen-point-to-ray
    UnityEngine.RectTransformUtility
    ScreenPointToRay
    (static: UnityEngine.Ray UnityEngine.Camera UnityEngine.Vector2))
  (define-method-port
    rectangle-contains-screen-point?
    UnityEngine.RectTransformUtility
    RectangleContainsScreenPoint
    (static:
      System.Boolean
      UnityEngine.RectTransform
      UnityEngine.Vector2
      UnityEngine.Camera)))
