(library (system transactions transaction)
  (export is?
          transaction?
          get-hash-code
          dispose
          rollback
          enlist-volatile
          enlist-promotable-single-phase?
          enlist-durable
          dependent-clone
          clone
          equals?
          current-get
          current-set!
          current-update!
          isolation-level
          transaction-information)
  (import (ironscheme-clr-port))
  (define (is? a) (clr-is System.Transactions.Transaction a))
  (define (transaction? a) (clr-is System.Transactions.Transaction a))
  (define-method-port
    get-hash-code
    System.Transactions.Transaction
    GetHashCode
    (System.Int32))
  (define-method-port
    dispose
    System.Transactions.Transaction
    Dispose
    (System.Void))
  (define-method-port
    rollback
    System.Transactions.Transaction
    Rollback
    (System.Void System.Exception)
    (System.Void))
  (define-method-port
    enlist-volatile
    System.Transactions.Transaction
    EnlistVolatile
    (System.Transactions.Enlistment
      System.Transactions.ISinglePhaseNotification
      System.Transactions.EnlistmentOptions)
    (System.Transactions.Enlistment
      System.Transactions.IEnlistmentNotification
      System.Transactions.EnlistmentOptions))
  (define-method-port
    enlist-promotable-single-phase?
    System.Transactions.Transaction
    EnlistPromotableSinglePhase
    (System.Boolean
      System.Transactions.IPromotableSinglePhaseNotification))
  (define-method-port
    enlist-durable
    System.Transactions.Transaction
    EnlistDurable
    (System.Transactions.Enlistment
      System.Guid
      System.Transactions.ISinglePhaseNotification
      System.Transactions.EnlistmentOptions)
    (System.Transactions.Enlistment
      System.Guid
      System.Transactions.IEnlistmentNotification
      System.Transactions.EnlistmentOptions))
  (define-method-port
    dependent-clone
    System.Transactions.Transaction
    DependentClone
    (System.Transactions.DependentTransaction
      System.Transactions.DependentCloneOption))
  (define-method-port
    clone
    System.Transactions.Transaction
    Clone
    (System.Transactions.Transaction))
  (define-method-port
    equals?
    System.Transactions.Transaction
    Equals
    (System.Boolean System.Object))
  (define-field-port
    current-get
    current-set!
    current-update!
    (static: property:)
    System.Transactions.Transaction
    Current
    System.Transactions.Transaction)
  (define-field-port
    isolation-level
    #f
    #f
    (property:)
    System.Transactions.Transaction
    IsolationLevel
    System.Transactions.IsolationLevel)
  (define-field-port
    transaction-information
    #f
    #f
    (property:)
    System.Transactions.Transaction
    TransactionInformation
    System.Transactions.TransactionInformation))
