(library (system component-model double-converter)
  (export new is? double-converter?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...)
         #'(clr-new System.ComponentModel.DoubleConverter a ...)))))
  (define (is? a) (clr-is System.ComponentModel.DoubleConverter a))
  (define (double-converter? a)
    (clr-is System.ComponentModel.DoubleConverter a)))
