(library (system diagnostics performance-counter)
  (export new
          is?
          performance-counter?
          begin-init
          increment-by
          next-value
          remove-instance
          next-sample
          decrement
          increment
          close-shared-resources
          end-init
          close
          default-file-mapping-size-get
          default-file-mapping-size-set!
          default-file-mapping-size-update!
          category-name-get
          category-name-set!
          category-name-update!
          counter-help
          counter-name-get
          counter-name-set!
          counter-name-update!
          counter-type
          instance-lifetime-get
          instance-lifetime-set!
          instance-lifetime-update!
          instance-name-get
          instance-name-set!
          instance-name-update!
          machine-name-get
          machine-name-set!
          machine-name-update!
          raw-value-get
          raw-value-set!
          raw-value-update!
          read-only?-get
          read-only?-set!
          read-only?-update!)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...)
         #'(clr-new System.Diagnostics.PerformanceCounter a ...)))))
  (define (is? a) (clr-is System.Diagnostics.PerformanceCounter a))
  (define (performance-counter? a)
    (clr-is System.Diagnostics.PerformanceCounter a))
  (define-method-port
    begin-init
    System.Diagnostics.PerformanceCounter
    BeginInit
    (System.Void))
  (define-method-port
    increment-by
    System.Diagnostics.PerformanceCounter
    IncrementBy
    (System.Int64 System.Int64))
  (define-method-port
    next-value
    System.Diagnostics.PerformanceCounter
    NextValue
    (System.Single))
  (define-method-port
    remove-instance
    System.Diagnostics.PerformanceCounter
    RemoveInstance
    (System.Void))
  (define-method-port
    next-sample
    System.Diagnostics.PerformanceCounter
    NextSample
    (System.Diagnostics.CounterSample))
  (define-method-port
    decrement
    System.Diagnostics.PerformanceCounter
    Decrement
    (System.Int64))
  (define-method-port
    increment
    System.Diagnostics.PerformanceCounter
    Increment
    (System.Int64))
  (define-method-port
    close-shared-resources
    System.Diagnostics.PerformanceCounter
    CloseSharedResources
    (static: System.Void))
  (define-method-port
    end-init
    System.Diagnostics.PerformanceCounter
    EndInit
    (System.Void))
  (define-method-port
    close
    System.Diagnostics.PerformanceCounter
    Close
    (System.Void))
  (define-field-port
    default-file-mapping-size-get
    default-file-mapping-size-set!
    default-file-mapping-size-update!
    (static:)
    System.Diagnostics.PerformanceCounter
    DefaultFileMappingSize
    System.Int32)
  (define-field-port
    category-name-get
    category-name-set!
    category-name-update!
    (property:)
    System.Diagnostics.PerformanceCounter
    CategoryName
    System.String)
  (define-field-port
    counter-help
    #f
    #f
    (property:)
    System.Diagnostics.PerformanceCounter
    CounterHelp
    System.String)
  (define-field-port
    counter-name-get
    counter-name-set!
    counter-name-update!
    (property:)
    System.Diagnostics.PerformanceCounter
    CounterName
    System.String)
  (define-field-port
    counter-type
    #f
    #f
    (property:)
    System.Diagnostics.PerformanceCounter
    CounterType
    System.Diagnostics.PerformanceCounterType)
  (define-field-port
    instance-lifetime-get
    instance-lifetime-set!
    instance-lifetime-update!
    (property:)
    System.Diagnostics.PerformanceCounter
    InstanceLifetime
    System.Diagnostics.PerformanceCounterInstanceLifetime)
  (define-field-port
    instance-name-get
    instance-name-set!
    instance-name-update!
    (property:)
    System.Diagnostics.PerformanceCounter
    InstanceName
    System.String)
  (define-field-port
    machine-name-get
    machine-name-set!
    machine-name-update!
    (property:)
    System.Diagnostics.PerformanceCounter
    MachineName
    System.String)
  (define-field-port
    raw-value-get
    raw-value-set!
    raw-value-update!
    (property:)
    System.Diagnostics.PerformanceCounter
    RawValue
    System.Int64)
  (define-field-port
    read-only?-get
    read-only?-set!
    read-only?-update!
    (property:)
    System.Diagnostics.PerformanceCounter
    ReadOnly
    System.Boolean))
