(library (system uri-format-exception)
  (export new is? uri-format-exception?)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...) #'(clr-new System.UriFormatException a ...)))))
  (define (is? a) (clr-is System.UriFormatException a))
  (define (uri-format-exception? a)
    (clr-is System.UriFormatException a)))
