(library (system io ports dcb)
  (export new
          is?
          dcb?
          set-values
          dcb-length-get
          dcb-length-set!
          dcb-length-update!
          baud-rate-get
          baud-rate-set!
          baud-rate-update!
          flags-get
          flags-set!
          flags-update!
          w-reserved-get
          w-reserved-set!
          w-reserved-update!
          xon-lim-get
          xon-lim-set!
          xon-lim-update!
          xoff-lim-get
          xoff-lim-set!
          xoff-lim-update!
          byte-size-get
          byte-size-set!
          byte-size-update!
          parity-get
          parity-set!
          parity-update!
          stop-bits-get
          stop-bits-set!
          stop-bits-update!
          xon-char-get
          xon-char-set!
          xon-char-update!
          xoff-char-get
          xoff-char-set!
          xoff-char-update!
          error-char-get
          error-char-set!
          error-char-update!
          eof-char-get
          eof-char-set!
          eof-char-update!
          evt-char-get
          evt-char-set!
          evt-char-update!
          w-reserved1-get
          w-reserved1-set!
          w-reserved1-update!)
  (import (ironscheme-clr-port))
  (define-syntax new
    (lambda (e)
      (syntax-case e ()
        ((_ a ...) #'(clr-new System.IO.Ports.DCB a ...)))))
  (define (is? a) (clr-is System.IO.Ports.DCB a))
  (define (dcb? a) (clr-is System.IO.Ports.DCB a))
  (define-method-port
    set-values
    System.IO.Ports.DCB
    SetValues
    (System.Void
      System.Int32
      System.IO.Ports.Parity
      System.Int32
      System.IO.Ports.StopBits
      System.IO.Ports.Handshake))
  (define-field-port
    dcb-length-get
    dcb-length-set!
    dcb-length-update!
    ()
    System.IO.Ports.DCB
    dcb_length
    System.Int32)
  (define-field-port
    baud-rate-get
    baud-rate-set!
    baud-rate-update!
    ()
    System.IO.Ports.DCB
    baud_rate
    System.Int32)
  (define-field-port
    flags-get
    flags-set!
    flags-update!
    ()
    System.IO.Ports.DCB
    flags
    System.Int32)
  (define-field-port
    w-reserved-get
    w-reserved-set!
    w-reserved-update!
    ()
    System.IO.Ports.DCB
    w_reserved
    System.Int16)
  (define-field-port
    xon-lim-get
    xon-lim-set!
    xon-lim-update!
    ()
    System.IO.Ports.DCB
    xon_lim
    System.Int16)
  (define-field-port
    xoff-lim-get
    xoff-lim-set!
    xoff-lim-update!
    ()
    System.IO.Ports.DCB
    xoff_lim
    System.Int16)
  (define-field-port
    byte-size-get
    byte-size-set!
    byte-size-update!
    ()
    System.IO.Ports.DCB
    byte_size
    System.Byte)
  (define-field-port
    parity-get
    parity-set!
    parity-update!
    ()
    System.IO.Ports.DCB
    parity
    System.Byte)
  (define-field-port
    stop-bits-get
    stop-bits-set!
    stop-bits-update!
    ()
    System.IO.Ports.DCB
    stop_bits
    System.Byte)
  (define-field-port
    xon-char-get
    xon-char-set!
    xon-char-update!
    ()
    System.IO.Ports.DCB
    xon_char
    System.Byte)
  (define-field-port
    xoff-char-get
    xoff-char-set!
    xoff-char-update!
    ()
    System.IO.Ports.DCB
    xoff_char
    System.Byte)
  (define-field-port
    error-char-get
    error-char-set!
    error-char-update!
    ()
    System.IO.Ports.DCB
    error_char
    System.Byte)
  (define-field-port
    eof-char-get
    eof-char-set!
    eof-char-update!
    ()
    System.IO.Ports.DCB
    eof_char
    System.Byte)
  (define-field-port
    evt-char-get
    evt-char-set!
    evt-char-update!
    ()
    System.IO.Ports.DCB
    evt_char
    System.Byte)
  (define-field-port
    w-reserved1-get
    w-reserved1-set!
    w-reserved1-update!
    ()
    System.IO.Ports.DCB
    w_reserved1
    System.Int16))
